version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.22 # Use a versão do seu Go
    steps:
      - checkout
      - run:
          name: "Build do Projeto"
          command: go build -v ./...
      - run:
          name: "Rodar Testes"
          command: go test -v ./...
workflows:
  sample:
    jobs:
      - build